# ---------------------------------------------------------------
# Basic
# ---------------------------------------------------------------

# Appearance
appearance:
  # Accent color
  # accent_color: '#2a2b33'

  # Set background
  # background: '#f5f7fa'
  # background: '//www.toptal.com/designers/subtlepatterns/patterns/confectionary.png #f5f7fa'
  # background: 'url(//www.toptal.com/designers/subtlepatterns/patterns/confectionary.png) #f5f7fa'

  # background can be an array, in which case, the second value
  # is used as the background when the sidebar is open, default to accent_color,
  # for the best appearance, Keep its accent consistent with accent_color
  # background:
  #   - 'url(//www.toptal.com/designers/subtlepatterns/patterns/confectionary.png) #f5f7fa'
  #   - '#2a2b33'

  # Maximum width of content
  # content_width: 640

# Sidebar profile
profile:
  # `email` will fallback to `hexo.config.email` if not specified
  email: 1355265122@qq.com

  # Avatar URL, email address will be used for gravatar(https://en.gravatar.com) avatar if not specified.
  avatar: http://prgs9av8q.bkt.clouddn.com/3157f860f0db1818.jpg

  bio: |
        ä¸€ä¸ªå°è™BEER
categories: /categories
tags: /tags

# Sidebar menu
menu:
  Home: /
  About: /about
  Links: /links
  Sign: /clockin
  # Sidebar social media
# Try to sort by changing the order of the keys
sns:
  # `email` will fallback to `profile.email` if not specified
  email: 1355265122@qq.com
  # `feed` will fallback to `hexo.config.feed.path` if not specified
  feed:
  github:
  twitter: https://twitter.com/yohahaonan
  facebook:
  google+:
  instagram: https://www.instagram.com/_haonan/
  tumblr:
  dribbble:
  telegram:
  youtube:
  hangouts:
  linkedin:
  pinterest:
  soundcloud:
  myspace:
  weibo:
  qq: 1355265122

# Sidebar footer
footer:
  # Default to `Â©year â€¢ author`, set to false to disable.
  # copyright:

  # Set to false to hide Hexo link.
  powered: false

  # Set to false to hide theme link.
  theme: false

  # Custom text.
  # custom: Hosted by <a target="_blank" rel="noopener"
  #   href="https://pages.coding.me"><b>Coding Pages</b></a>
  custom: Written by LIL PIG FROM LEOIO<br>Theme is provided by <a href="https://github.com/elmorec/hexo-theme-inside">Inside.</a><br>Viewer Â· <span id="busuanzi_value_site_pv"></span>
# ---------------------------------------------------------------
# Content
# ---------------------------------------------------------------

# Page
page:
  # Display Table of content, default to `true`
  # toc: false

  # Display reward, default to `false`
  # reward: true

  # Display copyright notice, default to `false`
  # copyright: true


# Post
post:
  # per_page: 10

  # Display Table of content, default to `true`
  toc: true

  # Display reward, default to `false`
  reward: true

  # Display copyright notice, default to `false`
  copyright: true
  

# Archive
archive:
  per_page: 10

# Tag
tag:
  per_page: 10

# Category
category:
  per_page: 10


# ---------------------------------------------------------------
# Content addons
# ---------------------------------------------------------------

# Prefix/Suffix content image's path, useful for CDN setting,
# for example: `![cat](images/cat.gif)` will convert to:
# <img src="https://cdn.example.com/images/cat.gif?m=webp&q=80" alt="cat">
assets:
  # prefix: 'https://cdn.example.com'
  # suffix: '?m=webp&q=80'

# Table of content, enabled by default, set to false to disable.
toc:
  # The depth of toc, default to `3`, maximum to `4`.
  # depth: 3

  # Showing index before title, eg. 1.1 title, default to `true`
  # index: true

# Reward
reward:
  # Text which shows at the top.
  # text: Buy me a cup of coffee â˜•.
  text: "å†™ä¸œè¥¿è¿™ä¹ˆç´¯ï¼Œç»™æˆ‘ä¹°ç“¶è‚¥å®…å¿«ä¹æ°´8ğŸ¥‚ã€‚å¯ä»¥é€šè¿‡åä¸¤ç§æ‰‹æ®µå…è´¹æ”¯æŒæˆ‘å“¦ã€‚"
  # Payment Methods
  #  - qrcode: url of the qrcode image
  #    url: link of the payment
  #    text: link text of the url
  # qrcode and url must be set at least one
  methods:
    - name: wechat
      qrcode: http://prgs9av8q.bkt.clouddn.com/qrwc.png
  #     url:
      text: ä½¿ç”¨å¾®ä¿¡æ”¯ä»˜
    - name: alipay
      qrcode: http://prgs9av8q.bkt.clouddn.com/zfb.jpg
  #     url:
      text: ä½¿ç”¨æ”¯ä»˜å®æ”¯ä»˜
    - name: alipay_free
      qrcode: http://prgs9av8q.bkt.clouddn.com/zfbhb.jpg
      text: æ”¯ä»˜å®å…è´¹æ‰«çº¢åŒ…
    - name: google_ad
      text: æ”¶çœ‹Googleå¹¿å‘Šæ”¯æŒæˆ‘
      url: http://lilpig.site/watchad
  #   - name: paypal
  #     qrcode:
  #     url:
  #     text:
  #   - name: bitcoin
  #     qrcode:
  #     url:
  #     text:

# Copyright notice
# You can also use front matter `copyright` to override this setting.
# copyright:
  # Display author, default to `true`
  # author: true

  # Display link, default to `true`
  # link: false

  # license: Attribution-NonCommercial-NoDerivatives 4.0 International
  #   (<a href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/\"
  #   rel=\"external nofollow noopener\" target=\"_blank\">CC BY-NC-ND 4.0</a>)

  # Display published date, default to `false`
  # published: false

  # Display updated date, default to `false`
  # updated: false

  # Custom text, override above settings
  # custom: my copyright

# Comments
# Built-in support Disqus (https://disqus.com) and LiveRe (https://livere.com),
# for other comment system, see plugins
comments:
  # disqus:
    # shortname: disqus_shortname
    # Or you can set disqus script URL directly
    # script: //disqus_shortname.disqus.com/embed.js
    # Autoload, default to `true`, set to `false` to display a button
    # autoload: false

  # livere:
    # uid: livere_uid
    # LiveRe script, default to `https://cdn-city.livere.com/js/embed.dist.js`
    # script:
    # Autoload, default to `true`, set to `false` to display a button
    # autoload: false


# ---------------------------------------------------------------
# Misc
# ---------------------------------------------------------------

# URL prefix for theme statics
# static_prefix:

# URL prefix for json data
# If your json file is put in a cdn server,
# set data_prefix as '//cdn.com/path/to/path/your_json_dir' and data_dir as 'your_json_dir'
# data_prefix:

# Folder where json file will be generated to, default to 'api'
# data_dir: api

# Favicon, default to `favicon.ico`
# favicon: favicon.ico

# Google analytics
# ga: UA-00000000-0

# SEO
seo:
  # Render structured-data in <head>, default to `false`
  # structured_data: true

# PWA
pwa:
  # Workbox (https://developers.google.com/web/tools/workbox/) is a JavaScript
  # libraries for adding offline support to web apps,
  # disabled by default, remove the hash to enable
  # workbox:
    # Workbox cdn, uses google by default, below is an example of using alicdn
    # cdn: https://g.alicdn.com/kg/workbox/3.3.0/workbox-sw.js
    # module_path_prefix: https://g.alicdn.com/kg/workbox/3.3.0/
    # Expire time in hour, 4 by default, set to 0 to be permanent,
    # caches will be forcibly deleted the next time the site is updated.
    # expire: 4
    # The worker script name, `sw.js` by default
    # name: sw.js
    # Custom rules
    # rules:
    #   - name: jsdelivr
    #     strategy: staleWhileRevalidate
    #     regex: https://cdn\\.jsdelivr\\.net
    #   - name: gtm
    #     strategy: staleWhileRevalidate
    #     regex: https://www\\.googletagmanager\\.com\?id=.*
    #   - name: gravatar
    #     strategy: staleWhileRevalidate
    #     regex: https://www\\.gravatar\\.com
    #   - name: theme
    #     strategy: staleWhileRevalidate
    #     regex: /.*\\.(?:js|css|woff2|png|jpg|gif)$
    #   - name: cdn
    #     strategy: staleWhileRevalidate
    #     regex: https://cdn\\.yourdomain\\.com
    #   - name: json
    #     strategy: cacheFirst
    #     regex: your_data_prefix/.*\\.json

  # manifest.json
  # manifest:
    # short_name:
    # name:
    # start_url: /
    # theme_color: '#2a2b33'
    # background_color: '#2a2b33'
    # icons:
    #   - src: icon-194x194.png
    #     sizes: 194x194 512x512
    #     type: image/png
    #   - src: icon-144x144.png
    #     sizes: 144x144
    #     type: image/png

# Plugins, inject html snippet to a specified position
#  - position: `sidebar` | `post` | `page` | `comments`, can be an array
#    template: html code
# For the lastest ES grammar and code minification
# Run the following command in the root directory of Hexo (not `themes/inside`):
# ```bash
# npm install babel-core babel-preset-env html-minifier uglify-js --save
# ``
# `
#

plugins: 
  - position: post
    template: |
      <script>
       window.MathJax && MathJax.Hub && MathJax.Hub.Queue(['Typeset', MathJax.Hub, document.querySelector('main')]);
      </script>
    mathjax: true
#- hexo-renderer-mathjax
    
  # - position:
  #   template:
search:
  # åœ¨é¡µé¢å³ä¸‹è§’çš„ FAB æŒ‰é’®é‡Œæ˜¾ç¤ºå¿«æ·æœç´¢å…¥å£
  fab: true

  # é¢å¤–ç”Ÿæˆ search é¡µé¢ï¼Œå¯é…ç½®åœ¨ sidebar å¯¼èˆªï¼Œå¦‚ `Search: /search`
  page: true

  # ä»¥ä¸Šä¸¤ä¸ªå…¥å£å¿…é¡»è‡³å°‘è®¾ç½®ä¸€ä¸ªï¼Œå¦åˆ™è§†ä¸ºæ— æ•ˆé…ç½®

  # æœ¬åœ°æœç´¢ï¼Œå³ç”Ÿæˆæœ¬åœ° json æ–‡ä»¶
  adapter:
    # json æ•°æ®çš„èŒƒå›´ï¼Œæ•°ç»„
    range:
      - post
      - page

    # json æ•°æ®çš„æ¡ç›®é™åˆ¶
    # å‡å¦‚ `limit:1000`ï¼ŒåŒæ—¶æœ‰ 800 ç¯‡ postï¼Œ800 ç¯‡ pageï¼Œåˆ™æœ€ç»ˆç”Ÿæˆçš„æ•°æ®åŒ…å«ï¼š
    # 800 ç¯‡ postï¼Œ200 ç¯‡ page
    # ç¼ºçœå€¼ `10000`
    limit: 10000

    # æœç´¢ç»“æœåˆ†é¡µå¤§å°ï¼Œç¼ºçœå€¼ `10`
    per_page: 5